
//import net.proteanit.sql.DbUtils;
//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.Statement;
//import java.sql.Connection;

///import com.mysql.jdbc.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Wethum Kawsika
 */
public class allstudent extends javax.swing.JFrame {
   //   Statement stmt=null;
      PreparedStatement st;
  //Connection con=null;
     
    /**
     * Creates new form 
     */
    public allstudent() {
        initComponents();
        DefaultTableModel model=(DefaultTableModel)view.getModel();
       // con=databaseConnection.connection();
        showdata("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();
        grade = new javax.swing.JComboBox<>();
        mainmenu = new javax.swing.JButton();
        editadd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        filter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setText("STUEDNTS OF  CLASS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 20, 416, 45);

        view.setBackground(new java.awt.Color(153, 102, 0));
        view.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17"
            }
        ));
        view.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(view);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(9, 143, 1250, 390);

        grade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-A", "1-B", "1-C", "1-D", " ", "2-A", "2-B", "2-C", "2-D", " ", "3-A", "3-B", "3-C", "3-D", " ", "4-A", "4-B", "4-C", "4-D", " ", "5-A", "5-B", "5-C", "5-D", " ", "6-A", "6-B", "6-C", "6-D", " ", "7-A", "7-B", "7-C", "7-D", " ", "8-A", "8-B", "8-C", "8-D", " ", "9-A", "9-B", "9-C", "9-D", " ", "10-A", "10-B", "10-C", "10-D", " ", "11-A", "11-B", "11-C", "11-D", " ", "12-A", "12-B", "12-C", "12-D", " ", "13-A", "13-B", "13-C", "13-D" }));
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });
        jPanel1.add(grade);
        grade.setBounds(510, 80, 102, 38);

        mainmenu.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        mainmenu.setText("MAIN MENU");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        jPanel1.add(mainmenu);
        mainmenu.setBounds(1120, 550, 140, 30);

        editadd.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        editadd.setText("EDIT/ADD");
        editadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaddActionPerformed(evt);
            }
        });
        jPanel1.add(editadd);
        editadd.setBounds(530, 550, 120, 30);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1190, 390, 37, 16);

        filter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        filter.setText("FILTER");
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        jPanel1.add(filter);
        filter.setBounds(670, 80, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void showdata(String d3) {
     //    Connection con=getConnection();
        // PreparedStatement st;
         ResultSet rs;
               try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
               Connection con=  DriverManager.getConnection("jdbc:MySQL://172.20.10.2:3306/schoolmanagement2","root","pass");
         Statement  stmt = con.createStatement();
            
            
            if (grade.getSelectedItem().equals("ALL")) {
                 st=con.prepareStatement("SELECT * FROM student Where Grade= ?");
                    st.setString(1, d3); 
                    
            } else {
                
                  
                   st = con.prepareStatement("SELECT * FROM student Where Grade= ? ");
           //st=con.clientPrepareStatement("SELECT * FROM first WHERE Section = ?");
                   
                    st.setString(1, d3);
             }
             
              rs=st.executeQuery();
             DefaultTableModel model=(DefaultTableModel)view.getModel();
             model.setRowCount(0);
             Object[] row;
             
             while(rs.next()){
                 row = new Object[17];
    row[0] = rs.getInt(1);
    row[1] = rs.getString(2);
    row[2] = rs.getString(3);
    row[3] = rs.getString(4);
    row[4] = rs.getString(5);
    row[5] = rs.getString(6);
    row[6] = rs.getString(7);
    row[7] = rs.getString(8);
    row[8] = rs.getString(9);
    row[9] = rs.getString(10);
    row[10] = rs.getString(11);
    row[11] = rs.getString(12);
    row[12] = rs.getString(13);
    row[13] = rs.getString(14);
    row[14] = rs.getString(15);
    row[15] = rs.getString(16);
    row[16] = rs.getString(17); 
                 model.addRow(row);
             }
           //  Table1.setModel(model);
         }
         catch(Exception e){
             System.out.println(e.getMessage() );
         }
     }
    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_gradeActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
         setVisible(false);
         Home vie=new Home();
         vie.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mainmenuActionPerformed

    private void editaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaddActionPerformed
       setVisible(false);
       student view=new student();
       view.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_editaddActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        try{
         view.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","Address","Grade","Birthday","Co-Activities","Extra-Activities","Gender","Admission","Gurdian","ContactNo","G_AddNo","G_AddYear","G_LeaveYear","SY_AddNo","SY_Grade","SY_Name"}));
        String gra=(String) grade.getSelectedItem();
        // TODO add your handling code here:
         showdata(gra);
            
         }
             
         catch(Exception e){
              System.out.println("Error in report generation: " + e.getMessage());
         }

    }//GEN-LAST:event_filterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editadd;
    private javax.swing.JButton filter;
    private javax.swing.JComboBox<String> grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainmenu;
    private javax.swing.JTable view;
    // End of variables declaration//GEN-END:variables
}
