
//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.Statement;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public final class CurrentPrinciple extends javax.swing.JFrame {
     private static String javaVersion;
//    Connection con = null;
//    Statement stmt = null;
//    ResultSet rs = null;

    /**
     * Creates new form CurrentPrinciple
     */
    public CurrentPrinciple() {
        initComponents();
      //  con = databaseConnection.connection();
        ViewPrinciple();
    }
    public void ViewPrinciple(){
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:MySQL://192.168.8.174:3306/schoolmanagement2","root","");
      
            Statement  stmt =  con.createStatement();
            
            String query = "SELECT * FROM principal WHERE pastpresent= 'PRESENT'";
            
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
                
                {
                name.setText(rs.getString("name"));
                address.setText(rs.getString("address"));
                age.setText(String.format("%s",rs.getInt("age")));
                birthday.setText(String.format("%tD", rs.getDate("birthday")));
                gender.setSelectedItem(rs.getString("gender"));
                contactno.setText(String.format("%s", rs.getInt("contact")));
                    
                BufferedImage image = ImageIO.read(rs.getBinaryStream("image"));
                ImageIcon.setIcon(new ImageIcon(image));
                }
            }
            
            
            
            
            
        }
        catch(Exception e){
            System.out.println(e);
            
            
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        imageicon = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        ImageIcon = new javax.swing.JLabel();
        editoradd = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        editoradd1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Principle");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 261, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setText("ADDRESS      ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 262, 147, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel4.setText("BIRTHDAY       ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 346, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel5.setText("GENDER      ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 388, 148, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel6.setText("CONTACT NO. ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 430, 150, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel8.setText("AGE                 ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 304, 159, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 222, 374, -1));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 264, 374, -1));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 306, 374, -1));
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 348, 374, -1));
        jPanel1.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 432, 374, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel10.setText("NAME");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 220, 76, -1));

        imageicon.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        imageicon.setText("SELECT IMAGE");
        imageicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageiconActionPerformed(evt);
            }
        });
        jPanel1.add(imageicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 152, -1, -1));

        gender.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "M", "F" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 391, 114, -1));
        jPanel1.add(ImageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 128, 137));

        editoradd.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        editoradd.setText("EDIT/ADD");
        editoradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editoraddActionPerformed(evt);
            }
        });
        jPanel1.add(editoradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 472, -1, -1));

        mainmenu.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        mainmenu.setText("MAIN MENU");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        jPanel1.add(mainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 116, -1));

        editoradd1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        editoradd1.setText("VICE PRINCIPALS >>");
        editoradd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editoradd1ActionPerformed(evt);
            }
        });
        jPanel1.add(editoradd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 563, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/princ.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 840, 690));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/princ.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 950, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageiconActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser ();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        ImageIcon.setIcon(new ImageIcon(file.toString()));
        filename=file.getAbsolutePath();
        
        
        try{
             File image = new File(filename);
             FileInputStream fis = new FileInputStream(image);
             ByteArrayOutputStream bos =new ByteArrayOutputStream();
             byte[] buf = new byte [1024];
             for(int readNum;(readNum = fis.read(buf)) != -1;){
                
             bos.write(buf, 0, readNum);
             }
             
             photo= bos.toByteArray();
             ImageIcon.setIcon(new ImageIcon(ImageIO.read(file)));
            
            
              
             
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_imageiconActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void editoraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editoraddActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Principle view = new Principle();
        view.setVisible(true);
        
        
    }//GEN-LAST:event_editoraddActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        Home view = new Home();
        view.setVisible(true);
    }//GEN-LAST:event_mainmenuActionPerformed

    private void editoradd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editoradd1ActionPerformed

          setVisible(false);
        vice_principal view = new vice_principal();
        view.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_editoradd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentPrinciple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentPrinciple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentPrinciple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentPrinciple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentPrinciple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageIcon;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField contactno;
    private javax.swing.JButton editoradd;
    private javax.swing.JButton editoradd1;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton imageicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainmenu;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

 byte [] photo = null;
 String filename = null;

}
