

import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Wethum Kawsika
 */
public class edit_vice_principal extends javax.swing.JFrame {
private static String javaVersion;
//    Connection con = null;
//    Statement stmt = null;
    /**
     * Creates new form edit_vice_principal
     */
    public edit_vice_principal() {
        initComponents();
          //con = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        pastpresent = new javax.swing.JComboBox<>();
        imageicon = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        ImageIcon = new javax.swing.JLabel();
        mainmenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VICE PrincipleS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 49));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS      ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 347, 147, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BIRTHDAY       ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 437, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENDER      ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 484, 148, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTACT NO. ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 535, 150, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AGE                 ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 393, 159, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 299, 374, 30));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 347, 374, 30));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 391, 374, 30));
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 435, 374, 31));
        jPanel1.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 532, 374, 33));

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 169, 37, 20));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 166, 230, 31));

        search.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NAME");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 301, 76, -1));

        add.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 149, -1));

        update.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 138, -1));

        pastpresent.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        pastpresent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAST/PRESENT", "PRESENT", "PAST" }));
        pastpresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastpresentActionPerformed(evt);
            }
        });
        jPanel1.add(pastpresent, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 215, 265, -1));

        imageicon.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        imageicon.setText("SELECT IMAGE");
        imageicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageiconActionPerformed(evt);
            }
        });
        jPanel1.add(imageicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 214, -1, -1));

        gender.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "M", "F" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 481, 96, 33));
        jPanel1.add(ImageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 171, 171));

        mainmenu.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        mainmenu.setText("MAIN MENU");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        jPanel1.add(mainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 123, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prin.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, -10, 1330, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:MySQL://192.168.8.174:3306/schoolmanagement2","root","");
      
            Statement  stmt = con.createStatement();
            int sId = Integer.parseInt(id.getText());
            String query = "SELECT * FROM vice_principal";
            ResultSet rs = stmt.executeQuery(query);

            while(rs.next()){
                if(sId == rs.getInt("id")){
                   // pastpresent.setText(rs.getString("pastpresent"));
                    name.setText(rs.getString("name"));
                    address.setText(rs.getString("address"));
                    age.setText(String.format("%s",rs.getInt("age")));
                    birthday.setText(String.format("%tD", rs.getDate("birthday")));
                    gender.setSelectedItem(rs.getString("gender"));
                    contactno.setText(String.format("%s", rs.getInt("contact")));
                    
                     pastpresent.setSelectedItem(rs.getString("pastpresent"));
                    BufferedImage image = ImageIO.read(rs.getBinaryStream("image"));
                    ImageIcon.setIcon(new ImageIcon(image));

                }

            }
        } catch (Exception e) {
            System.out.println( e);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:MySQL://192.168.8.174:3306/schoolmanagement2","root","");
      
            Statement  stmt = con.createStatement();

            int sId=Integer.parseInt(id.getText());
            String sName=name.getText();
            String sAddress=address.getText();
            int sAge=Integer.parseInt(age.getText());
            long sbday=Date.parse(birthday.getText());
            java.sql.Date bday=new java.sql.Date(sbday);  String bdayString = birthday.getText();
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                   Date parsedDate = dateFormat.parse(bdayString);
            // java.sql.Date bday = new java.sql.Date(parsedDate.getTime());
            String sGender=(String)gender.getSelectedItem();
            int sContact = Integer.parseInt(contactno.getText());
            String PastPresent = (String) pastpresent.getSelectedItem();
            //tttvhvgu
            String query="INSERT INTO vice_principal (id,name,address,age,birthday,gender,contact,image,pastpresent)VALUES(?,?,?,?,?,?,?,?,?)";

            PreparedStatement preparedStmt=con.prepareStatement(query);
            preparedStmt.setInt(1,sId);
            preparedStmt.setString(2,sName);
            preparedStmt.setString(3,sAddress);
            preparedStmt.setInt(4, sAge);
            preparedStmt.setDate(5,bday);
            preparedStmt.setString(6,sGender);
            preparedStmt.setInt(7, sContact);
            preparedStmt.setBytes(8,photo);
            preparedStmt.setString(9,PastPresent);

            preparedStmt.execute();
            JOptionPane.showMessageDialog(null, "ADDED");

        }
        catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:MySQL://192.168.8.174:3306/schoolmanagement2","root","");
      
            Statement  stmt = con.createStatement();

            int sId=Integer.parseInt(id.getText());
            String sName=name.getText();
            String sAddress=address.getText();
            int sAge=Integer.parseInt(age.getText());
            //long sbday=Date.parse(birthday.getText());
              String bdayString = birthday.getText();
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                   Date parsedDate = dateFormat.parse(bdayString);
             java.sql.Date bday = new java.sql.Date(parsedDate.getTime());
            //java.sql.Date bday=new java.sql.Date(sbday);
            String sGender=(String)gender.getSelectedItem();
            int sContact = Integer.parseInt(contactno.getText());
            String PastPresent = (String) pastpresent.getSelectedItem();

            //tttvhvgu
            String query ="UPDATE vice_principal SET name = ?,address = ?,age = ?, birthday = ?,gender = ?,contact = ?,image =?,pastpresent=? WHERE id = ?";

            PreparedStatement preparedStmt=(PreparedStatement) con.prepareStatement(query);

            preparedStmt.setString(1,sName);
            preparedStmt.setString(2,sAddress);
            preparedStmt.setInt(3, sAge);
            preparedStmt.setDate(4,bday);
            preparedStmt.setString(5,sGender);
            preparedStmt.setInt(6, sContact);
            preparedStmt.setBytes(7,photo);
            preparedStmt.setString(8,PastPresent);
            preparedStmt.setInt(9,sId);

            preparedStmt.executeUpdate();
            JOptionPane.showConfirmDialog(null, "UPDATED");

        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void pastpresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastpresentActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pastpresentActionPerformed

    private void imageiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageiconActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser ();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        ImageIcon.setIcon(new ImageIcon(file.toString()));
        filename=file.getAbsolutePath();

        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos =new ByteArrayOutputStream();
            byte[] buf = new byte [1024];
            for(int readNum;(readNum = fis.read(buf)) != -1;){

                bos.write(buf, 0, readNum);
            }

            photo= bos.toByteArray();
            ImageIcon.setIcon(new ImageIcon(ImageIO.read(file)));

        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_imageiconActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
           setVisible(false);
        Home view = new Home();
        view.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mainmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_vice_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_vice_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_vice_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_vice_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_vice_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageIcon;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField contactno;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton imageicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainmenu;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> pastpresent;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
     byte [] photo = null;
    String filename = null;
}
