
//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.PreparedStatement;
//import com.mysql.jdbc.Statement;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
//import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Teacher extends javax.swing.JFrame {
    private static String javaVersion;
//    Connection con = null;
//    Statement stmt = null;

    
     
     

    /**
     * Creates new form Teacher
     */
    public Teacher() {
       initComponents();
     //  con = databaseConnection.connection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        New = new javax.swing.JButton();
        search = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        ImageIcon = new javax.swing.JLabel();
        imageicon = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12ebab398af2453fa99529f2d378d7b8.jpeg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEACHER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 43, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 241, 37, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 283, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BIRTHDAY");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GENDER");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONTACT NO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 493, -1, -1));

        id.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 374, -1));

        name.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 286, 374, -1));

        address.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 370, -1));

        birthday.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 374, -1));

        contactno.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jPanel1.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 496, 374, -1));

        gender.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 157, -1));

        submit.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        update.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));

        New.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        New.setText("NEW");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        jPanel1.add(New, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 132, -1, -1));

        search.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 132, -1, -1));

        delete.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, -1, -1));

        ImageIcon.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ImageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 28, 140, 150));

        imageicon.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        imageicon.setText("SELECT IMAGE");
        imageicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageiconActionPerformed(evt);
            }
        });
        jPanel1.add(imageicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tee.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 0, 710, 760));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12ebab398af2453fa99529f2d378d7b8.jpeg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -90, 670, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void imageiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageiconActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser ();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        ImageIcon.setIcon(new ImageIcon(file.toString()));
        filename=file.getAbsolutePath();
        
        
        try{
             File image = new File(filename);
             FileInputStream fis = new FileInputStream(image);
             ByteArrayOutputStream bos =new ByteArrayOutputStream();
             byte[] buf = new byte [1024];
             for(int readNum;(readNum = fis.read(buf)) != -1;){
                  bos.write(buf, 0, readNum);
             }
             
             photo= bos.toByteArray();
             ImageIcon.setIcon(new ImageIcon(ImageIO.read(file)));
            
              
             
        }
        catch(Exception e){
            System.out.println(e);
        }
        
       
            
    }//GEN-LAST:event_imageiconActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:MySQL://172.20.10.2:3306/schoolmanagement2","root","pass");
      
            Statement  stmt = con.createStatement();
          
            int sId=Integer.parseInt(id.getText());
            String sName=name.getText();
            String sAddress=address.getText();
            String bdayString = birthday.getText();
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                   Date parsedDate = dateFormat.parse(bdayString);
             java.sql.Date bday = new java.sql.Date(parsedDate.getTime());

             
            //long sbday=Date.parse(birthday.getText());
            //java.sql.Date bday=new java.sql.Date(sbday);
            String sGender=(String)gender.getSelectedItem();
            int sContact = Integer.parseInt(contactno.getText());
            //tttvhvgu
            String query="INSERT INTO teacher (id,name,address,birthday,gender,contact,image)VALUES(?,?,?,?,?,?,?)";
       
            PreparedStatement preparedStmt=(PreparedStatement) con.prepareStatement(query);
            preparedStmt.setInt(1,sId);
            preparedStmt.setString(2,sName);
            preparedStmt.setString(3,sAddress);
           // preparedStmt.setInt(4, sAge);
            preparedStmt.setDate(4,bday);
            preparedStmt.setString(5,sGender);
            preparedStmt.setInt(6, sContact);
            preparedStmt.setBytes(7,photo);
            
            preparedStmt.execute();
            JOptionPane.showConfirmDialog(null, "ADDED");
            
}
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:MySQL://172.20.10.2:3306/schoolmanagement2","root","pass");
      
            Statement  stmt =  con.createStatement();
          
            int sId=Integer.parseInt(id.getText());
            String sName=name.getText();
            String sAddress=address.getText();
           
           String bdayString = birthday.getText();
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                   Date parsedDate = dateFormat.parse(bdayString);
             java.sql.Date bday = new java.sql.Date(parsedDate.getTime());

            String sGender=(String)gender.getSelectedItem();
            int sContact = Integer.parseInt(contactno.getText());
            //tttvhvgu
            String query ="UPDATE teacher SET name = ?,address = ?, birthday = ?,gender = ?,contact = ?,image =? WHERE id = ?";
       
            PreparedStatement preparedStmt=(PreparedStatement) con.prepareStatement(query);
            
            preparedStmt.setString(1,sName);
            preparedStmt.setString(2,sAddress);
                        preparedStmt.setDate(3,bday);
            preparedStmt.setString(4,sGender);
            preparedStmt.setInt(5, sContact);
            preparedStmt.setBytes(6,photo);
            preparedStmt.setInt(7,sId);
            
            preparedStmt.executeUpdate();
            JOptionPane.showConfirmDialog(null, "UPDATED");
            
}
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:MySQL://172.20.10.2:3306/schoolmanagement2","root","pass");
      
            Statement  stmt = con.createStatement();
            
            int sId =Integer.parseInt(id.getText());
            
            String query =" DELETE FROM teacher WHERE id = "+sId+" ";
            
            stmt.executeUpdate(query);
            Reset();
            JOptionPane.showConfirmDialog(null, "DELETED");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_NewActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:MySQL://172.20.10.2:3306/schoolmanagement2","root","pass");
      
            Statement  stmt = con.createStatement();
            int sId = Integer.parseInt(id.getText());
            String query = "SELECT * FROM teacher";
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
                if(sId == rs.getInt("id")){
                    name.setText(rs.getString("name"));
                    address.setText(rs.getString("address"));
                    //age.setText(String.format("%s",rs.getInt("age")));
                    birthday.setText(String.format("%tD", rs.getDate("birthday")));
                    gender.setSelectedItem(rs.getString("gender"));
                    contactno.setText(String.format("%s", rs.getInt("contact")));
                    
                    BufferedImage image = ImageIO.read(rs.getBinaryStream("image"));
                    ImageIcon.setIcon(new ImageIcon(image));
                    
                    
                    
                    
                }
                
                
            }
        } catch (Exception e) {
            System.out.println( e);
        }
        
            
    }//GEN-LAST:event_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         setVisible(false);
       Home view=new Home();
       view.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed
    public void Reset(){
        id.setText("");
        name.setText("");
        address.setText("");
        
        birthday.setText("");
        gender.setSelectedItem("");
        contactno.setText("");
        imageicon.setIcon(null);
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageIcon;
    private javax.swing.JButton New;
    private javax.swing.JTextField address;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField contactno;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton imageicon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JButton search;
    private javax.swing.JButton submit;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
    byte []photo =null;
    String filename = null;

}